### PR TITLE
Include tip for using jlink

### PR DESCRIPTION
**Pull request by SueChaplain**
If translations from English are not required,
tell users how to exclude the translated property
files, which reduces the size of the image.

Closes: #308

Signed-off-by: Sue Chaplain <sue_chaplain@uk.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by dinogun** [comment]
Minor update, the command to exclude files should be `--exclude-files=**java_**.properties` instead of `--exclude-files=**java_*.properties` (Notice the `**`).

I have a Dockerfile that works with the above change [here](https://github.com/dinogun/watson-springboot/blob/master/docker/Dockerfile.openj9.v11.jlink#L32). This is inline with what the [jlink](https://docs.oracle.com/javase/9/tools/jlink.htm#JSWOR-GUID-CECAC52B-CFEE-46CB-8166-F17A8E9280E9) documentation says.
@pshipton

**Comment by SueChaplain** [comment]
Thanks @dinogun 

>Minor update, the command to exclude files should be --exclude-files=**java_**.properties instead of --exclude-files=**java_*.properties (Notice the **).

Fixed

**Comment by SueChaplain** [comment]
@pshipton  - are you ok with these changes?

**Comment by pshipton** [comment]
Yes, I was waiting to see if anyone else had comments.

**Pull request merged**
