### PR TITLE
Store Unsafe classes in shared class cache (-XX:[+/-]ShareUnsafeClasses)

### LINKED ISSUE #351: Document new command line options: -XX:[+/-]ShareUnsafeClasses
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/7149

**Overview:**
Add new command line options -XX:[+/-]ShareUnsafeClasses, which allow to enable and disable storing and finding classes created through Unsafe.defineClass in the shared class cache. The default is enabled.

**Release target:**
Eclipse OpenJ9 Release 0.17 (Java 8, 11, 13) Oct refresh

**Applies to the following JDK versions:**
All JDK versions

**Applies to the following platforms:**
All platforms

**For new command line options:**

- **Option name and syntax:** -XX:[+/-]ShareUnsafeClasses
- **Purpose:** Provides the ability to enable and disable storing and finding Unsafe classes in the shared class cache

### PR DESCRIPTION
**Pull request by pmhayward**
Resolves #351

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@pshipton , @DanHeidinga Would appreciate a review of the first draft of new topic for the [-XX:[+/-]ShareUnsafeClasses option](https://eclipse.github.io/openj9-docs-staging/371/xxshareunsafeclasses/). Is the -XX:[+|-]ShareAnonymousClasses still OK as is, or is that option affected by this new one?
371

**Comment by DanHeidinga** [comment]
Draft looks good.  The `-XX:[+|-]ShareAnonymousClasses option` doesn't need to change.

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Pull request merged**
