### PR TITLE
Tidy information about Balanced GC

### PR DESCRIPTION
**Pull request by pmhayward**
Edit information added to gc.md about Balanced GC, arraylets, and double mapping. 
Fix links. 
Replace first diagram in this section
Add entry in 0.19 "What's new"

References #475, #476

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by amicic** [comment]
Enabling double mapping by default has been deferred. It will not be a part of 0.19. We don't need to document it now.

Some general documentation about Balanced GC that does not talk about double mapping could go in, but it's probably easier to just defer this update altogether.

**Comment by SueChaplain** [comment]
That's bad news @amicic and @bragaigor - a lot of this stuff already went in. We thought it was all enabled, so merged Igor's updates. This PR is to do some further editing on the input.

**Comment by amicic** [comment]
We were not sure up until the last moment of code split if it will be enabled or not. Don't know if this was early enough, but I tried to notify Peter that deferral is likely to happen here: https://github.com/eclipse/openj9/issues/8349#issuecomment-583448629

**Comment by SueChaplain** [comment]
NP  - we can merge and hide it until 0.20.0. Leaving with Peter to address

**Pull request merged**
