### PR TITLE
Remove support for Windows 8.1, Server 2012, but not R2

### LINKED ISSUE #556: Remove OpenJ9 support for Windows 8 and Server 2012
**Subject:**
https://www.eclipse.org/openj9/docs/openj9_support/

**Suggestion:**
Although technically Windows 8.1 and Server 2012 are in extended support until 2023, effectively the OpenJ9 committers don't have easy access to these platforms if needed to support them. They may still work as the build platform is currently Windows Server 2012 R2, but they aren't tested.

Windows Server 2012 R2 should be used instead, although it's also in extended support until only 2023 so a newer version is recommended.

### PR DESCRIPTION
**Pull request by pshipton**
Closes #556

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
LGTM

**Comment by pshipton** [comment]
@SueChaplain can we get his change into the live version of the docs?

**Comment by SueChaplain** [comment]
@pshipton Sure - if you patch the openj9-docs-0.20.0 branch we can rebuild it.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9-docs/pull/560

**Pull request merged**
