### PR TITLE
Deprecate XX:IdleTuningCompactOnIdle and add dependency to gcOnIdle

### LINKED ISSUE #277: Deprecate XX:IdleTuningCompactOnIdle
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/5374

**Overview:**
Heuristics for determining when to compact on idle will be added in the near future.

Once the heuristics are added, XX:IdleTuningGcOnIdle will control both GC and compact,
and as such, there is no need for a distinct option to control compaction.

Related [comment](https://github.com/eclipse/openj9/issues/5374#issuecomment-495269609) about this deprecation

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux X|P|Z*

### PR DESCRIPTION
**Pull request by ShishirH**
Heuristics for determining when to compact on idle will be added in the near future.

Once the heuristics are added, XX:IdleTuningGcOnIdle will control both GC and compact,
and as such, there is no need for a distinct option to control compaction.

See [issue](https://github.com/eclipse/openj9/issues/5374), and related comment about [deprecation](https://github.com/eclipse/openj9/issues/5374#issuecomment-495269609)

Also updated the behaviour of compactOnIdle to reflect its new dependency on gcOnIdle, when this [PR](https://github.com/eclipse/openj9/pull/5894) will be merged.

Release level: Eclipse OpenJ9 V0.15.0

Fixes #277 

Signed-off-by: Shishir Halaharvi <shishir.neo95@gmail.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
@ShishirH - please confirm when the OMR/OpenJ9 changes are merged so that I don't put this one in ahead of the code.

Can you also confirm that https://www.eclipse.org/openj9/docs/introduction/#cloud-optimizations does not need an update. It mentions compaction, but the statement might still hold true after the changes.

Please also check the text in the other related topics, some of which refer to this option. Text might need amending there too. (-XXIdleTuningGCOnIdle / -XXIdleTuningMinFreeHeapOnIdle / XXIdleTuningMinIdleWaitTime)

Finally, the release topic will need updating to indicate this change in behaviour (version.0.15.md ... merging soon for another 0.15 change)

**Comment by SueChaplain** [comment]
@ShishirH - please also indicate the release level that this deprecation occurs in so that users can understand when the removal is likely. So, presumably **Eclipse OpenJ9 V0.15.0**.

**Comment by ShishirH** [comment]
@SueChaplain The OpenJ9 changes have been merged [here](https://github.com/eclipse/openj9/pull/5894).

Can confirm that https://www.eclipse.org/openj9/docs/introduction/#cloud-optimizations does not need any changes. 

No other changes are required in either `XX:IdleTuningGCOnIdle`, `XX:IdleTuningMinFreeHeapOnIdle`, or `XXIdleTuningMinIdleWaitTime

Yes, the release level is Eclipse OpenJ9 V0.15.0

**Comment by SueChaplain** [comment]
@ShishirH 

https://www.eclipse.org/openj9/docs/xxidletuningminidlewaittime/:

>Garbage collection and compaction are controlled by the -XX:+IdleTuningGcOnIdle and -XX:+IdleTuningCompactOnIdle options,

https://www.eclipse.org/openj9/docs/xxidletuninggconidle/:

>In a container environment, the VM also attempts to compact the object heap before releasing memory by default, which is controlled by the  -XX:[+|-]IdleTuningCompactOnIdle option. 

These statements can no longer be true based on your description in the issue:

>Once the heuristics are added, XX:IdleTuningGcOnIdle will control both GC and compact,
and as such, there is no need for a distinct option to control compaction.

Please also add the release number to the deprecation statement.

Please also scan and ensure that any links or references to XX:IdeTuningCompactOnIdle mention deprecation. For example, the **See Also** links should call out that the option is deprecated:

>See also
>-XX:IdleTuningMinIdleWaitTime
>-XX:IdleTuningMinFreeHeapOnIdle
>-XX:[+|-]IdleTuningCompactOnIdle (deprecated)

**Comment by ShishirH** [comment]
@SueChaplain  I'm sorry, I should have been more clear in my description. 

> https://www.eclipse.org/openj9/docs/xxidletuningminidlewaittime/:
> 
> > Garbage collection and compaction are controlled by the -XX:+IdleTuningGcOnIdle and -XX:+IdleTuningCompactOnIdle 

This holds true even after the OpenJ9 merge. Work is being done to add the heuristics to `XX:IdleTuningGcOnIdle`, so that everything is controlled by that option itself, with no need for a separate `XX:IdleTuningCompactOnIdle`. However, that is going to be another PR, unrelated to the current change that got merged. I doubt that will be ready by the 15 release.

As such, both GC and compaction are still controlled by the options GcOnIdle and CompactOnIdle even now.

Should this be updated even then? Maybe mention that in future all functionality is going to be combined in `IdleTuningGcOnIdle`?

> https://www.eclipse.org/openj9/docs/xxidletuninggconidle/:
> 
> > In a container environment, the VM also attempts to compact the object heap before releasing memory by default, which is controlled by the  -XX:[+|-]IdleTuningCompactOnIdle option.

Same goes for this.

Will make the suggested changes.

**Comment by SueChaplain** [comment]
@ShishirH  - any progress on this PR please?

**Comment by ShishirH** [comment]
The heuristics for replacing CompactOnIdle have been merged in OMR [here](https://github.com/eclipse/omr/pull/3939). Will make the necessary changes

**Comment by SueChaplain** [comment]
@ShishirH @pshipton - I believe this doc update should be completed for our milestone 1 release. Please confirm. If you are unable to get it done, I will do it.

**Comment by ShishirH** [comment]
Deleted the branch in my local repo accidentally, and the changes aren't reflecting now. Will create a new PR

**Comment by ShishirH** [comment]
Link to the new PR: https://github.com/eclipse/openj9-docs/pull/314

**Pull request closed without merging**
