### PR TITLE
New Footer and Navbar similar to the new site

### PR DESCRIPTION
**Pull request by Bazif-Khan**

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@Bazif-Khan ... Hi Bazif. New footer looks good and works nicely on mobile too! 
Could you make a small tweak, though. Not sure whether it was deliberate or just a consequence, of another change, but there's now a thick black line at the end of every topic, just above the footer, which wasn't there before. Not sure it's necessary and I think it would look better without. Could you change the style sheet(?) so that it doesn't appear? Thanks!

**Comment by Bazif-Khan** [comment]
Jenkins doc stage

**Comment by Bazif-Khan** [comment]
It was due to `theme/partials/previous_next.html`. I have already deleted the file. If you update the staging site, then that thick line shouldn't be there.

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Ah!... Have respun staging build and now all looks good. Thanks!

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Pull request merged**
