### PR TITLE
SUPERSEDED: Add extended information for Balanced GC

### PR DESCRIPTION
**Pull request by pmhayward**
This includes information about arraylets, but does not currently mention double mapping.
(also fixes typo in name of arraylet_diagram.png)

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Closing. This work is now applied via other PRs.

**Pull request closed without merging**
