### PR TITLE
Remove documentation of restriction on multi-layer shared cache.

### LINKED ISSUE #457: Remove restriction on multi-layer shared cache
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/7955*

**Overview:**
*Previously we documented the restriction of multi-layer shared cache here:
https://eclipse.github.io/openj9-docs-staging/385/xshareclasses/#layer*

> Restriction: The jvmtiSharedCacheInfo.isCorrupt field and the SharedClassCacheInfo.isCacheCorrupt() method cannot detect a corrupted cache that has a layer number other than 0. However, when a VM starts a layered cache directly, for example when you specify the -Xshareclasses:name=<cache_name> option on the command line, the VM detects any corruption and generates an error message as usual, regardless of the layer number of the cache.

Such restriction can be removed.

**Release target:**
*Eclipse OpenJ9 0.18.0*

**Applies to the following JDK versions:**
*All*

**Applies to the following platforms:**
*All 64-bit platforms*

**For new command line options:**
N.A.
- Purpose:
- Restrictions:

### PR DESCRIPTION
**Pull request by hangshao0**
Closes #457

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Should the removal of this restriction be mentioned in the release topic?

**Comment by hangshao0** [comment]
> Should the removal of this restriction be mentioned in the release topic?

I don't know how did you handle such case in the past. But I am fine with mentioning this in the release topic if you want.

**Comment by pshipton** [comment]
We might as well at it to the list, then users have notification of the change.

**Comment by hangshao0** [comment]
Updated the release topic.

**Comment by pshipton** [comment]
@SueChaplain the code is delivered, this is ok to merge.

**Pull request merged**
