### PR TITLE
Modify -Xdump for writing to STDOUT/STDERR

### LINKED ISSUE #204: Print a javacore dump to STDOUT and STDERR
https://github.com/eclipse/openj9/issues/2837#issuecomment-458884303
https://github.com/eclipse/openj9/pull/4521

**Overview:**
Give user options to print a javacore dump to STDOUT/ERR rather than printing to a file.

Applies to all JDK version

Applies to all platforms

-Xdump:java:file=/STDOUT/ 
-Xdump:java:file=/STDERR/ 

This option is non case sensitive (eg: `/stdout/` will also work.

You can also print to STDOUT with -Xdump:java:file=-

Add the option -Xdump:java:file=/STDOUT/ to print a javacore dump to STDOUT
Add the option -Xdump:java:file=/STDERR/ to print a javacore dump to STDERR

### PR DESCRIPTION
**Pull request by pmhayward**
Resolves #204

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Pull request merged**
