### PR TITLE
Make container build more robust

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Add timeout set to 6 hours
- Add timestamps to console output
- Clean workspace at end of build
- Add tar.gz extension to archive name

Issue #1

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins build container

**Comment by AdamBrousseau** [comment]
Jenkins build container

**Comment by AdamBrousseau** [comment]
Jenkins build container

**Comment by AdamBrousseau** [comment]
Jenkins build container

**Comment by AdamBrousseau** [comment]
Jenkins build container

**Comment by AdamBrousseau** [comment]
Jenkins build container

**Comment by AdamBrousseau** [comment]
Unmarking this as WIP, #45 seems to have resolved the docker issues.
@SueChaplain I think this is ready to be merged

**Comment by SueChaplain** [comment]
Thanks @AdamBrousseau.

**Pull request merged**
