### PR TITLE
Adapt docs colour palette and remove Google Analytics

### PR DESCRIPTION
**Pull request by pmhayward**

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins docs stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by AdamBrousseau** [comment]
Jenkins doc stage

**Pull request merged**
