### PR TITLE
Upate to latest container

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Also install tzdata first

Issue #914

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
jenkins build container

**Comment by AdamBrousseau** [comment]
jenkins build container

**Comment by doveye** [comment]
Thanks for the PR, though the ID team had planned on creating one when we're ready to get the levels updated (probably week after next). We would want to specify Ubuntu 20.04 though, so we don't end up encountering issues with a later level of Ubuntu that we haven't tested on.

**Comment by AdamBrousseau** [comment]
Feel free to create one. I can close this. I was curious and wanted to test out the changes mentioned in the issue.

**Comment by doveye** [comment]
Ah, I see. Hopefully it all worked!

**Comment by doveye** [comment]
Closing as this was eventually superseded by the PRs for #914

**Pull request closed without merging**
