### PR TITLE
Increase clone & checkout timeout to 30 minutes

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Fixes eclipse-openj9/openj9#13745

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins doc stage

**Comment by pshipton** [comment]
```
09:10:12  Fetching upstream changes from https://github.com/eclipse-openj9/openj9-docs-staging
09:10:12   > git --version # timeout=10
09:10:12   > git --version # 'git version 2.15.0'
09:10:12   > git fetch --tags --progress -- https://github.com/eclipse-openj9/openj9-docs-staging +refs/heads/*:refs/remotes/origin/* # timeout=30
09:12:58  ERROR: Error fetching remote repo 'origin'
09:12:58  hudson.plugins.git.GitException: Failed to fetch from https://github.com/eclipse-openj9/openj9-docs-staging
09:12:58  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1004)
09:12:58  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1245)
09:12:58  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
09:12:58  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
09:12:58  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
09:12:58  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
09:12:58  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
09:12:58  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$558/0x0000000000000000.run(Unknown Source)
09:12:58  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
09:12:58  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
09:12:58  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:12:58  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:12:58  	at java.base/java.lang.Thread.run(Thread.java:836)
09:12:58  Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/eclipse-openj9/openj9-docs-staging +refs/pull/860/merge:refs/remotes/origin/pr/860/merge" returned status code 128:
09:12:58  stdout: 
09:12:58  stderr: fatal: Couldn't find remote ref refs/pull/860/merge
```

**Comment by AdamBrousseau** [comment]
Jenkins doc stage

**Comment by AdamBrousseau** [comment]
Jenkins doc stage

**Pull request merged**
