### PR TITLE
Add jvmti and dtfj topics / add Diagnostics section to toc

### LINKED ISSUE #132: Document JVMTI GetOSThreadID() extension
**Subject:**
The JVMTI extensions are not yet documented, but when they are, the GetOSThreadID() extension is missing from the list at https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/jvmti_extensions_ref.html

**Suggestion:**
This extension returns the OS thread id in the threadid_ptr parameter, that corresponds to the jthread parameter.

jvmtiError GetOSThreadID(jvmtiEnv* jvmti_env, jthread thread, jlong * threadid_ptr);

### PR DESCRIPTION
**Pull request by pmhayward**
Fix incorrect links.
Fixes #132

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
For the record we should be a little more explicit in the PR about what is being added. i.e. JVMTI, DTFJ, and MXBean as people looking at a list of commits won't necessarily realise the extent of the changes. So please edit/update the commit message.

I found a couple of places in the OpenJ9 user docs that link to JVMTI, DTFJ and MXBean (*New to OpenJ9* and *Tools and Data*) in the old doc set, so these will need to be updated. Could be other places too, so worth a scan.

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Pull request merged**
