### PR TITLE
Enable LUDCL by default for 0.18.0

### PR DESCRIPTION
**Pull request by theresa-m**
Fixes: #413 

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@SueChaplain @doveye this should be reviewed, but I've marked it WIP so it doesn't get merged before the OpenJ9 side change are ready.

**Comment by SueChaplain** [comment]
We need an issue for this please.

**Comment by theresa-m** [comment]
@SueChaplain the issue is https://github.com/eclipse/openj9-docs/issues/413

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@pshipton ... I see that this is no longer "WIP" - does that mean it's ready to be merged?

**Comment by pshipton** [comment]
@pmhayward the associated OpenJ9 PRs are not yet all approved. Plus there is a merge conflict here.

**Comment by DanHeidinga** [comment]
The OpenJ9 PRs for this item have all been merged now.

**Comment by DanHeidinga** [comment]
Change looks good to me.  @pmhayward This can be merged once the doc team OKs it

**Pull request merged**
