### PR TITLE
API documentation styling fix

### PR DESCRIPTION
**Pull request by Bazif-Khan**
Signed-off-by: Bazif Khan <bazif.khan@ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Bazif. Your mkdocs.yaml file is very old and it looks like a merge will cause breaking changes. Can you check please.

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by Bazif-Khan** [comment]
> Bazif. Your mkdocs.yaml file is very old and it looks like a merge will cause breaking changes. Can you check please.

@doveye sent me mkdocs.yaml file and I'm using that.

**Comment by doveye** [comment]
That was my local mkdocs.yaml file, it was only supposed to be for test purposes.

**Pull request merged**
