### PR TITLE
Hamburger menu in mobile view fixed

### PR DESCRIPTION
**Pull request by Bazif-Khan**
Signed-off-by: Bazif Khan <bazif.khan@ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by Bazif-Khan** [comment]
fixes: https://github.com/eclipse/openj9-docs/issues/420

**Comment by SueChaplain** [comment]
LGTM

**Pull request merged**
