### PR TITLE
Add links to option-builder tools

### PR DESCRIPTION
**Pull request by pmhayward**
Xdump and Xtrace topics modified and new tool_builder file added to yml

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
LGTM +1

**Pull request merged**
