### PR TITLE
Doc update: Shared classes cache layers 2

### PR DESCRIPTION
**Pull request by doveye**
Add restriction and printTopLayerStats. Move printStats and printAllStats from IBM KC doc to OpenJ9.

https://github.com/eclipse/openj9-docs/issues/368

Signed-off-by: Esther Dovey doveye@uk.ibm.com

[skip ci]

### CODE REVIEW

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
This work is not complete, but Esther is now on vacation. Closing this PR and continuing the work in a separate PR.

**Pull request merged**
