### PR TITLE
Add JITServer helm chart availability

### PR DESCRIPTION
**Pull request by SueChaplain**
- available since 0.24.0

Closes: #743

Signed-off-by: SueChaplain <sue_chaplain@uk.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Review by mpirvu — APPROVED** [review]
LGTM

**Pull request merged**
