### PR TITLE
INACTIVE: Update docs for Class Relationship Verification Snippets

### PR DESCRIPTION
**Pull request by sharon-wang**
Fixes: https://github.com/eclipse/openj9-docs/issues/490
Class Relationship Verification Snippets PR: https://github.com/eclipse/openj9/pull/8420 

Changes:
- [x] Add new documentation for `-XX:[+|-]ClassRelationshipVerifierIgnoreSCC`
- [x] Update `-Xfuture` to include incompatibility with IgnoreSCC option
- [x] Update `-Xverify` to include incompatibility with IgnoreSCC option
- [x] Update `-XX:[+|-]ClassRelationshipVerifier` to refer to IgnoreSCC option if user does not want to use SCC for Class Relationship Verification
- [x] Update Shared classes cache diagnostic utilities (printStats) to include Snippets
- [x] Update Java dump to include Snippets
- [ ] Update release documentation to describe difference between `-XX:[+|-]ClassRelationshipVerifier` and `-XX:[+|-]ClassRelationshipVerifierIgnoreSCC`
- [ ] Update release documentation to note that the shared classes cache generation number has been updated, similar to: https://www.eclipse.org/openj9/docs/version0.14/#changes-to-the-shared-classes-cache-generation-number

### CODE REVIEW

**Comment by pmhayward** [comment]
This looks good to merge. Needs entry in "What's new" (`version0.19.md`), but I can fix that later with general tidying up.

**Comment by sharon-wang** [comment]
Thanks for reviewing Peter! I'm not sure which release this work will go into yet, so I'll leave this as WIP. I'm thinking it won't go in until 0.20 or later. Will update once known

**Comment by pmhayward** [comment]
@sharon-wang ... Hi Sharon,  Just keeping tabs on outstanding doc issues. Is this one likely to be in the 0.22.0 release, or is it deferred for the time being? Thanks!

**Comment by sharon-wang** [comment]
@pmhayward This work will not be in the 0.22.0 release. The PR/review for the related OpenJ9 change is inactive, as such I don't have an outlook on which release it might go into. I will change "WIP" in this title to "Inactive" to better reflect the state. Thanks for checking!

**Comment by pmhayward** [comment]
@sharon-wang  Thanks for updating

**Comment by SueChaplain** [comment]
I propose to close this PR as it is very old with respect to the current code base. If these changes are still planned, please rebase and raise a new PR.

**Comment by sharon-wang** [comment]
I'm not sure about the plans for these changes -- I think it makes sense to close this, as there are merge conflicts that would need to be addressed whenever this work gets picked up, if it does.

**Pull request closed without merging**
