### PR TITLE
OpenJ9 uses gcc 7.5 to compile on Linux

### LINKED ISSUE #520: Linux switched to gcc 7.5 for compilation
**Issue or pull request number:**
https://github.com/AdoptOpenJDK/openjdk-build/issues/1508
https://github.com/eclipse/openj9/pull/8443
https://github.com/eclipse/openj9/pull/8559

**Overview:**
OpenJ9 uses gcc 7.5 to compile on Linux.

**Release target:**
OpenJ9 0.19 and all nightly builds

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
Linux X|P|Z

### PR DESCRIPTION
**Pull request by pshipton**
Closes #520

### CODE REVIEW

**Comment by pshipton** [comment]
I'd like to remove Java 13 from the page, when can that be done?

**Comment by DanHeidinga** [comment]
> I'd like to remove Java 13 from the page, when can that be done?

As soon as JDK14 ships I'd say

**Comment by DanHeidinga** [comment]
@SueChaplain Change looks fine.  Tagging you for a review to ensure that this is OK to merge now given the upcoming release

**Comment by pshipton** [comment]
> I'd like to remove Java 13 from the page, when can that be done?

>> As soon as JDK14 ships I'd say

That should mean we can remove it today, as merged changes won't go live until JDK14 ships.

**Comment by SueChaplain** [comment]
Our way of working thus far when we've added a feature release has been to remove the earlier release at the next quarterly update. The thinking behind this is to give users a small amount of time to switch their dev environments to the new feature release. Having said that, I am not against removing the build tables or supported environment topics. We can remove or update the rest of the references in the docs for 0.20.0.

**Comment by pshipton** [comment]
I've resolved the merge conflict and removed the jdk13 tables.

**Pull request merged**
