### PR TITLE
Add new -XX topic for container support

### LINKED ISSUE #24: Setting a new default maximum heap size for applications running in containers
To cover the work done in https://github.com/eclipse/openj9/pull/1517 and https://github.com/eclipse/openj9/pull/1797.

New topic for -XX:+UseContainerSupport, with supporting content

### PR DESCRIPTION
**Pull request by pmhayward**
File xxusecontainersupport.md added and .yml file updated
(base.html also tweaked to remove GitHub edit 'pencil' icon from H1 headers)

Fixes #24

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@pshipton - please review this new topic for the -XX:UseContainerSupport option at http://staging.eclipse.org/openj9/docs/xxusecontainersupport/index.html
Thanks!

**Comment by pshipton** [comment]
I can't get to the staging link. It wants a username and password, but I can't get it to accept anything.

**Comment by pshipton** [comment]
Looking at the files, I think we need to say more about what -XX:UseContainerSupport does.
@deesebas @ashu-mehra

**Comment by pmhayward** [comment]
@deesebas @ashu-mehra ... Can I give you a nudge to provide a bit more about what -XX:UseContainerSupport does? Thanks!

**Comment by ashu-mehra** [comment]
@pmhayward my suggestion is to add something like this:

# -XX:[+|-]UseContainerSupport

This option causes OpenJ9 to recognize if it is running in a container environment and tune itself based on the resource limits imposed by the container.
Currently the tuning is limited to adjusting the maximum Java heap size to a larger fraction of memory limit imposed by the container. Note that this adjustment is done only if the container imposes memory limit.
The following table shows the maximum Java heap size that gets set depending on the container's memory limit:

| Container memory | Maximum Java heap size  |
|--------------------------------|-------------------------|
| Less than 1 GB                 | 50% *&lt;size&gt;*      |
| 1 GB - 2 GB                    | *&lt;size&gt;* - 512 MB |
| Greater than 2 GB              | 75% *&lt;size&gt;*      |

## Syntax
	-XX:[+|-]UseContainerSupport

| Setting | Effect | Default |
|---|---|---|
|`-XX:+UseContainerSupport`  | Enable | |
|`-XX:-UseContainerSupport`  | Disable| Default |

**Comment by ashu-mehra** [comment]
@pshipton we don't have much to say about -XX:+UseContainerSupport  as of now, other than change in the max heap size (see https://github.com/eclipse/openj9-docs/pull/37#issuecomment-396232754).
I guess it would be better if we add more text as and when other changes are done, right?

**Comment by pshipton** [comment]
It also affects -XX:MaxRAMPercentage and -XX:InitialRAMPercentage I thought, as it enables determining the container limit.

**Comment by ashu-mehra** [comment]
@pshipton ok, I have added a sentence about that in the comment.

**Pull request merged**
