### PR TITLE
Flag ExitOnOutOfMemory does not exist  >> ExitOnOutOfMemoryError

### PR DESCRIPTION
**Pull request by Herr-Sepp**
-XX:+ExitOnOutOfMemory does nothing.

What this docfile is about: -XX:+ExitOnOutOfMemoryERROR
See the commit for this flag: https://github.com/eclipse/openj9/pull/7406

Signed-off-by: Sepp Bauer Herr-Sepp@outlook.com

### CODE REVIEW

**Comment by SueChaplain** [comment]
@Herr-Sepp Thank you for identifying this error in the documentation. I can see a few places where changes are needed to fully correct the problem. 

Unfortunately your PR failed a check. In order to contribute to an Eclipse project you must sign the Eclipse Contributor Agreement, which is quite straightforward (Go to https://www.eclipse.org/ and log in -> create a new account. The ECA should be something you can click on when your profile is created)

If you do not want to sign the ECA for some reason, we will happily process the changes on your behalf. However, we hope that you do and continue take an interest in the OpenJ9 project.

**Comment by pshipton** [comment]
@theresa-m fyi

**Comment by Herr-Sepp** [comment]
i have sign the eca but the check says:

>  Failures
> Sepp Bauer (Herr-Sepp@****.com) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.

I am not sure what i need to do, because i have this footer added to my commit.

**Comment by pshipton** [comment]
The Signed-off-by needs to be added to the commit message, it's not needed in the PR description. The commit needs to be modified and force pushed.

**Comment by pshipton** [comment]
A valid Signed-off-by looks like `Peter Shipton <Peter_Shipton@ca.ibm.com>`. You should set user.name and user.email in your git global config, and use the git commit -s or --signoff option to have it automatically signed.

**Comment by Herr-Sepp** [comment]
Thank you for your help with this.

**Comment by SueChaplain** [comment]
@Herr-Sepp - glad you have managed to successfully pass the checks!

The change in filename to the xxexitonoutofmemory.md file is going to cause a couple of broken links. 

- https://eclipse.github.io/openj9-docs/version0.18/#new-exit-dump-agent-and-exitonoutofmemoryerror-option
- https://eclipse.github.io/openj9-docs/cmdline_migration/       -  link is in the table, the option name is also incorrectly recorded.

Are you able to update your commit to fix these items too please?

**Comment by pmhayward** [comment]
@Herr-Sepp, @SueChaplain ... As well as updating links in version0.18.md and cmdline_migration.md, the relevant entry in the mkdocs.yml file will need to be fixed.

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@Herr-Sepp ... All looks good and links working properly
Thanks for spotting this error and providing a fix.

**Pull request merged**
