### PR TITLE
New -XX[+|-]ClassRelationshipVerifier command line option

### LINKED ISSUE #360: Document new command line options: -XX:[+|-]ClassRelationshipVerifier
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/7089

**Overview:**
Add a new command line option `-XX:[+|-]ClassRelationshipVerifier`, which allows users to enable/disable recording and validating class relationships in the verifier.

**Release target:**
Eclipse OpenJ9 0.17.0

**Applies to the following JDK versions:**
All JDK versions.

**Applies to the following platforms:**
All platforms.

**For new command line options:**

- **Option name and syntax:** `-XX[+|-]ClassRelationshipVerifier`
- **Purpose:** To avoid unnecessary class loads, which reduces VM startup time.
- **Restrictions:** Cannot be used with `-Xfuture`. Note that `-Xverify:all` also enables `-Xfuture`.

### PR DESCRIPTION
**Pull request by pmhayward**
Resolves #360

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@sharon-wang , @DanHeidinga , @pshipton  Please review this draft. You can follow link in "What's New" topic... https://eclipse.github.io/openj9-docs-staging/376/version0.17/#option-to-record-class-relationships-in-the-verifier
I couldn't see mention of default state, so made a guess (50/50 chance!) - please confirm.

**Comment by sharon-wang** [comment]
@pmhayward Thanks for putting this together. The default state is disabled, so your guess is spot on!

Just a couple comments: 
- in the "What's New" blurb, `...for programs execution and loads only...` can be changed to `...for a program's execution, thus loading only...`
- in the Setting table on the -XX:[+|-]ClassRelationshipVerifier page, the square brackets `[ ]` around the enable `[+]` and disable `[-]` should be removed

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@sharon-wang ... thanks for updates: now done

**Pull request merged**
