### PR TITLE
Refix broken links in footer

### PR DESCRIPTION
**Pull request by pmhayward**
Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Seems to be consistently working.

**Comment by keithc-ca** [comment]
How long does it take for changes to propagate to https://www.eclipse.org/openj9/docs/ (because the links are broken as I write this)?

**Comment by SueChaplain** [comment]
They'll work when we publish the release next week.

**Comment by keithc-ca** [comment]
The are broken again. I've opened #719.

**Pull request merged**
