### PR TITLE
Java dump now includes CPU feature information

### PR DESCRIPTION
**Pull request by SueChaplain**
Add to release topic and update the example shown in the Java dump file.

Closes: #705

Signed-off-by: SueChaplain <sue_chaplain@uk.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Comment by pshipton** [comment]
lgtm
@harryyu1994 @fjeremic pls review

**Comment by fjeremic** [comment]
@harryyu1994 could we link the PR/issue on the OpenJ9 repo which implemented this? Many thanks for this work by the way!

**Comment by harryyu1994** [comment]
> @harryyu1994 could we link the PR/issue on the OpenJ9 repo which implemented this? Many thanks for this work by the way!

https://github.com/eclipse/openj9/pull/11215

**Review by fjeremic — APPROVED** [review]

**Comment by pshipton** [comment]
@SueChaplain did you want to squash before this is merged?

**Review by pshipton — APPROVED** [review]

**Pull request merged**
