### PR TITLE
Document -XX:[+|-]CompactStrings

### LINKED ISSUE #348: Document -XX:[+|-]CompactStrings
**Issue or pull request number:**
N/A

**Overview:**
Document the availability of the String compression feature in OpenJ9 which completes JEP 254 [1].

**Release target:**
Eclipse OpenJ9 0.8.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: -XX[+|-]CompactStrings
- Purpose: Provides heap space savings by using an ISO8859-1 internal character representation for String objects while preserving full API compatibility and improving performance under certain conditions. This feature is in general beneficial when most, or all Strings the user application uses can be encoded using the ISO8859-1 character encoding.
- Default value: -XX:-CompactStrings

[1] https://openjdk.java.net/jeps/254

### PR DESCRIPTION
**Pull request by pmhayward**
Resolves #348

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@fjeremic (fyi @DanHeidinga) Please confirm that this command is correctly documented.
A draft version is staged here:
https://eclipse.github.io/openj9-docs-staging/350/xxcompactstrings/
and also mentioned here, under "Compatible options":
https://eclipse.github.io/openj9-docs-staging/350/cmdline_migration/

**Comment by pmhayward** [comment]
@fjeremic   - Filip, Happy to add your extra comments, but I'm a bit confused about "with OpenJ9 the user does not pay any performance penalty for disabling the feature since the JIT is tuned to optimize specifically for Compact Strings."
1. If there's no performance hit if disabling feature, why bother enabling it?! (Or does that imply that you're not including savings in heap space as part of "performance"?)
2. Not sure how the "since" works! - How does Jit being optimised for Compact Strings explain why there's no performance hit when Compact Strings aren't being used?
Thanks

**Comment by fjeremic** [comment]
It's a matter of perspective, i.e. what your baseline is.

> 1. If there's no performance hit if disabling feature, why bother enabling it?! (Or does that imply that you're not including savings in heap space as part of "performance"?)

Enabling compact Strings will benefit via heap savings if most or all Strings in the application can be represented via the ISO8859-1 encoding. If this is not the case then we will have a mix of compressed Strings and decompressed Strings which is not ideal for performance.

> 2. Not sure how the "since" works! - How does Jit being optimised for Compact Strings explain why there's no performance hit when Compact Strings aren't being used?

Compact Strings are currently disabled by default, however the code to enable them is present. What is meant by "performance penalty for disabling" is that turning the feature off (as is the current default) has no performance implications on the application, even though for all String APIs we have to make checks all the time for "are compact Strings enabled?". The JIT optimizes away all such checks, so the application does not pay a performance penalty if it doesn't want compact Strings.

**Comment by pmhayward** [comment]
Jenkins doc stage

**Comment by pmhayward** [comment]
@fjeremic ... thanks for the explanation; I'm much clearer now! 
I've updated the topic here: https://eclipse.github.io/openj9-docs-staging/350/xxcompactstrings/
If you're OK with that, I'll merge the PR.

**Pull request merged**
