### PR TITLE
Add new z/OS dump token %sysname

### PR DESCRIPTION
**Pull request by pshipton**
Fixes https://github.com/eclipse/openj9-docs/issues/724

### CODE REVIEW

**Comment by pshipton** [comment]
@SueChaplain do you think I should add this to the release notes, considering there is no OpenJ9 z/OS build?

**Comment by pshipton** [comment]
@SueChaplain how do you want to handle this?

**Comment by SueChaplain** [comment]
Sorry @pshipton - I missed your earlier comment and didn't look as it was still *draft*. I think we should add it to the release notes as we do call out support for z/OS in "About the docs". 

Minor comment - you have a misplaced "only".

>The following tokens are applicable only to z/OS:

**Comment by SueChaplain** [comment]
Jenkins doc stage

**Review by SueChaplain — APPROVED** [review]
LGTM

**Pull request merged**
