### PR TITLE
Add support for Hotspot GC option

### PR DESCRIPTION
**Pull request by gza060625**
https://github.com/eclipse/openj9-docs/issues/622
 https://github.com/eclipse/openj9/pull/10386

Adding documentation to include the following new options:
-XX:[+|-]AlwaysPreTouch

Do not merge until *after* 0.22.0

Signed-off-by: Enson Guo <enson.guo@ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
Hi gza060625 Enson, please also open an issue for this using the template so that the project leads can confirm which OpenJ9 release you are targeting for this change: https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md Thank you!

**Comment by gza060625** [comment]
@SueChaplain Hi Sue, is it too late to set release target to 0.22?

**Comment by amicic** [comment]
I just merged https://github.com/eclipse/openj9/pull/10386 into the master branch. So the option/feature won't be available in 0.22 release, but the next one.

**Comment by gza060625** [comment]
@SueChaplain Can I get a committer to review? Thanks.

**Comment by pmhayward** [comment]
Jenkins doc stage

**Pull request merged**
